# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b196b3617e7ffbc50d63496c386c6f1ec961998ca68dd3c7388be5b2806491dc76041a26cffe3c77b5614da05ed0e125a78bb44e05ac22364db25102585d389
  crest_id: <%= ENV["CLIENT_ID"] %>
  crest_secret: <%= ENV["SECRET_KEY"] %>
  alliance_id: <%= ENV["ALLIANCE_ID"] %>

test:
  secret_key_base: 9fd02a598ed3ce052ae9dade2eb20cd0472ae320051e1f2b8dcb61f43294c9780a4cfef77c479f111dd227938bde0ecf83b424f6478a07de53c44df75dfb5619
  crest_id: <%= ENV["CLIENT_ID"] %>
  crest_secret: <%= ENV["SECRET_KEY"] %>
  alliance_id: <%= ENV["ALLIANCE_ID"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  crest_id: <%= ENV["CLIENT_ID"] %>
  crest_secret: <%= ENV["SECRET_KEY"] %>
  alliance_id: <%= ENV["ALLIANCE_ID"] %>
